### ISSUE TITLE
Source API documentation

### ISSUE THREAD

**Issue by mgaastra** [drakhart/ha-super-soco-custom#14]
Hi,

I got inspired by your application and want to use the API to pull the data from my TC MAX to do some analyses on battery use, range, etc.

I was wondering where you got the information for the API, since I am searching but can not find any documentation on it.

Also I noticed that you have two files for the API (vmoto_soco_api.py and super_soco_api.py) which one should I use to retrieve the data?

Kind regards,

Mathijs

**Comment by drakhart** [comment]
Hi, Mathijs. Thanks for taking interest in this project.

Unfortunately there's no official documentation for the APIs, since I believe that Vmoto Soco never intented to open them to pulbic use besides the mobile apps. Everything I did was sniffing the network traffic from those apps and reverse engineering their code.

At some point I'll upload these API implementations to PyPI, but for now feel free to grab any of the files you mentioned and use them. There's one for the original API (`super_soco_api.py`) and one for the new API made available for newer bikes and replacement ECUs (`vmoto_soco_api.py`), so it depends on the mobile app you used to register your bike.

Best,

Brian
