### ISSUE TITLE
App Vmoto Soco

### ISSUE THREAD

**Issue by Erzo-github** [drakhart/ha-super-soco-custom#5]
My IMEI does not work on the Super Soco android app, but it works on the Vmoto Soco android app. Are you planning to make a Home assistant for the Vmoto Soco app as well?

**Comment by drakhart** [comment]
Hi, @Erzo-github! Thanks for stopping by and sharing your thoughts.

Yes, support for Vmoto Soco app compatible bikes is planned. I already have the new API specification and I'm only missing some serious spare time to get to work.

I'll let you know when it's available for testing.

**Comment by Erzo-github** [comment]
Great.

**Comment by Xnygra** [comment]
Hi drakhart, 

As from january 1st the old android app is no longer working, and we have to move over to the new Vmoto Soco App (after a new ECU is installed on warranty) Appreciate that you doing this on your spare time, but have you had a chance to look at this. 

The integration to Home Assistant is fabulous as i can (or could at least) have HA to control the charging the batteries to only 80% and hopefully get them to last a bit longer.

**Comment by drakhart** [comment]
Hi, @Xnygra. Thank you for taking interest in this custom component.

I have started working on the Vmoto Soco app compatibility, but progress will be slow due to some difficulties (namely the new two step authentication on this app and abstracting everything so both APIs con live together) and lack of time, so I can't make any promises on a deadline. It'll be ready when it's ready.

I'll update you when the first experimental version is available.

**Comment by drakhart** [comment]
Support for Vmoto Soco app has been added in [release 1.0.0-beta.7](https://github.com/drakhart/ha-super-soco-custom/releases/tag/1.0.0-beta.7).

Please note that this release contains many changes, some of them breaking for specific entities, so I recommend removing and setting up the integration again.

Enjoy and please let me know if you find any issues with it.
